### PR TITLE
Add explicit imports for dependencies and fix bugs

### LINKED ISSUE #48: devtools::install() does not take care of package dependencies
I removed the explicit calling of library dependencies in #45 and `devtools::install()` should mimic the same environment, since all of the packages are listed in the DESCRIPTION file. 

It does not - I return this error ` could not find function "."`

### PR DESCRIPTION
**Pull request by kelshmo**
This PR fixes #48 and includes a workaround that will be addressed in #59. 

It also: 

- Fixes warning with `pkdown.yaml` by adding that file to the `.Rbuildignore` file.
- Three functions are explicitly exported with Kara's hack in #48 to allow `cqn::cqn` to execute without error.
- Warnings are suppressed for `cqn::cqn` since I have no control over the warning `The use of 'sig2' is deprecated; do specify 'sigma' (= sqrt(sig2)) instead ` and I don't think it impacts functionality
- `edgeR` and `ggplot2` are recommended to be loaded in the "Run the plan" vignette to workaround #59.

### CODE REVIEW

File: R/plan.R [hunk 1]
```diff
@@ -24,25 +24,25 @@ rnaseq_plan <- function(metadata_id, metadata_version, counts_id,
                         biomart_id, biomart_version, host, filters,
                         organism){
   drake::drake_plan(
-    import_metadata = get_data(!!metadata_id,
+    import_metadata = sageseqr::get_data(!!metadata_id,
```
Comment (karawoo) [inline R/plan.R:27]: It shouldn't be necessary to prefix these function calls with `sageseqr::`, was there something not working that prompted this addition?

Comment (kelshmo) [reply R/plan.R]: It was complaining that it could not find `sageseqr::cqn` but I believe it was due to how I ordered the @export calls with `cqn`, `mclust` and `quantreg`; I fixed this before I created the PR. 

I tested removing this prefix with `devtools::check()` and did not pass a warning, so I removed them.

**Comment by karawoo** [comment]
This needs `devtools::document()` to be re-run to avoid the warning, otherwise looks good.

I often set the CI suite to fail on warnings so I can catch them more easily, if you want to do that you could put `error_on = "warning")` [here](https://github.com/kelshmo/sageseqr/blob/10d658c1b46d2ebe9e097045a2ee4bd6a7c80f62/.github/workflows/R-CMD-check.yaml#L17) (just a thought though).
